# Generated by Django 4.1 on 2025-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(default='', max_length=255)),
                ('marca', models.CharField(default='', max_length=255)),
                ('ano', models.IntegerField(default=1900)),
                ('descricao', models.TextField(default='', max_length=255)),
                ('vendido', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation date of the user', verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
